use_frameworks!

platform :ios, '10.0'

target 'THetFoundation_Example' do
  pod 'THetFoundation', :path => '../'

  target 'THetFoundation_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
